server:
  port: 8761

spring:
  application:
    name: eureka-server
  # Zipkin Properties - DISABLED FOR LOCAL RUN
  # zipkin:
  #   base-url: http://localhost:9411
  # Sleuth Properties - DISABLED FOR LOCAL RUN
  # sleuth:
  #   sampler:
  #     probability: 1.0

# Eureka Properties
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
    prefer-ip-address: true
